### ISSUE TITLE
Question about the name

### ISSUE THREAD

**Issue by kt3k** [Kimeiga/bahunya#3]
I've been using tacit for long time, and I'm now very interested in this project as well.

I have a question. What does the name of the project mean? The logo and some wikipedia pages seem implying [this flower](https://en.wikipedia.org/wiki/Bauhinia_%C3%97_blakeana), but I don't find what language bahunya come from. ([The turkish page](https://tr.wikipedia.org/wiki/Bauhinia_blakeana) seems calling it bahunya, but I'm not sure if it's turkish or not.)

**Comment by Kimeiga** [comment]
Hi Yoshiya! Glad to help add to the variety of classless CSS! :)

Here's the origin story of Bahunya copied and pasted from my medium article introducing it!

https://medium.com/ucladevx/i-created-a-10kb-classless-css-framework-5d5eff56837d


## Origin Story
Bahunya’s logo is a derivative of the Hong Kong flag!

I really like the shapes of the flag of Hong Kong, and wanted to create a logo out of it. So I made a similar flower with 6 pedals rather than 5. The flower of Hong Kong’s flag is the illusive Hong Kong Orchid Tree, aka Bauhinia blakeana. In Turkish, we call the Bauhinia, Bahunya. I added Century Schoolbook “Bahunya” under the logo I made, and everything fit! A framework’s identity was born.

**Comment by kt3k** [comment]
Thanks for sharing the story! What a exotic name! I love it 😄👍

**Comment by Kimeiga** [comment]
happy to add a little middle eastern vibe to the front end world :)

**Comment by Kimeiga** [comment]
Hi Yoshiya! 

Well it took 4 years but I completely reworked the whole framework to make it look a lot more professional and usable. 

If you decided to use it anywhere you'll have to drop in the new CDN link as I have changed the folder structure quite a lot.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kimeiga/bahunya/dist/bahunya.min.css">
```

Cheers and thanks for making an issue so long ago!

**Comment by kt3k** [comment]
Hi!

> Well it took 4 years but I completely reworked the whole framework to make it look a lot more professional and usable.

It's good to know bahunya updated very much! (looks supporting more elements now?)

I still love classless css concept. Currently I use [sakura](https://github.com/oxalorg/sakura) for my blog and tacit for my homepage, but I might find some usage of bahunya for something else. Thanks for updating!
