### ISSUE TITLE
overflow-x:auto on table's parent

### ISSUE THREAD

**Issue by GabrielDelepine** [Kimeiga/bahunya#4]
Hi,

Thank you so much for this wonderful project! It deserves 10x more stars.

There is only one trick I need to use to make `<table>` mobile compatible.

 ```javascript
<div style="overflow-x: auto;">
  <table>
    ...
  </table>
</div>
```

**It produces this result:** 

<img width="651" alt="Screenshot 2020-05-11 at 16 06 05" src="https://user-images.githubusercontent.com/1979087/81571451-416f0000-93a2-11ea-8110-0859f8753200.png">
<img width="651" alt="Screenshot 2020-05-11 at 16 06 13" src="https://user-images.githubusercontent.com/1979087/81571468-492ea480-93a2-11ea-9872-39ebc32a4d9a.png">

**Without it's clearly worse:**

<img width="651" alt="Screenshot 2020-05-11 at 16 06 36" src="https://user-images.githubusercontent.com/1979087/81571514-577cc080-93a2-11ea-98f5-09e87a65b00d.png">

---

PS: I don't know why Bahunya gives a `overflow-x: auto` to the `table`. What's the purpose?

<img width="308" alt="Screenshot 2020-05-11 at 16 14 09" src="https://user-images.githubusercontent.com/1979087/81571728-a1fe3d00-93a2-11ea-8d61-19eeb4c4c6a8.png">

**Comment by Kimeiga** [comment]
HEY! I apologize for the lack of communication but I'm basically almost done revamping the entire framework to be lighter, have a more internally consistent codebase, and basically look a lot better. When I release i'll let you know.

I will double check if I've fixed this issue with the tables because I've actually completely redid them from scratch instead of relying on the code from tacit that I started with.

I think they should be the correct width both standalone and within smaller containers but I shall check.

I will probably finish this after finals week so basically this summer so sorry for the further delay!

**Comment by Kimeiga** [comment]
Hi Gabriel!

Well it took 4 years and redoing the whole css framework to fix it and make it look nicer but I made sure `<tables>`s overflow nicely on small screens. #1 mentioned this as well, and I just fixed it over there.

The new framework has `<table>`s be marked as `display: block` to allow them to overflow while still looking good normally.

You'll have to drop in the new CDN link as I have changed the folder structure quite a lot.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kimeiga/bahunya/dist/bahunya.min.css">
```

Cheers and thanks for making an issue so long ago!
